---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.4

inputs:
  - name: dp-csv-splitter
    path: go/src/github.com/ONSdigital/dp-csv-splitter

outputs:
  - name: bin

run:
  path: go/src/github.com/ONSdigital/dp-csv-splitter/ci/scripts/build.sh
